name: Publish Python Package to PyPI
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.4'
      - name: Configure Poetry and publish package to PyPI
        run: |
          poetry config http-basic.pypi "__token__" "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build
